version: 2
updates:
  # Python (uv)
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - x86txt
    labels:
      - dependencies

  - package-ecosystem: pip
    directory: /api
    schedule:
      interval: weekly
    reviewers:
      - x86txt
    labels:
      - dependencies

  # TS/JS (pnpm)
  - package-ecosystem: pnpm
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - x86txt
    labels:
      - dependencies

  - package-ecosystem: pnpm
    directory: /frontend
    schedule:
      interval: weekly
    reviewers:
      - x86txt
    labels:
      - dependencies
